<script setup>
import {ref,computed,onMounted,onUnmounted,nextTick} from 'vue';
import AppIcon from './AppIcon.vue';
import {loadRecentLogins,rememberLogin,matchingLogins,offerPasswordSave} from './loginPreferences.js';
import release from '../../release.json';
const availableRelease=ref(null),showRelease=ref(false);
let releaseTimer;
async function checkRelease(){
 if(document.hidden)return;
 try{const response=await fetch('/version.json',{cache:'no-store'});if(!response.ok)return;const next=await response.json();if(typeof next.version==='string')availableRelease.value=next.version!==release.version?next:null}catch{}
}
function refreshVersion(){if(modal.value){flash('Сохраните или закройте текущую форму перед обновлением.');return}location.reload()}
onMounted(()=>{checkRelease();releaseTimer=setInterval(checkRelease,60000)});
onUnmounted(()=>clearInterval(releaseTimer));
const vModalFocus={mounted(el){el._previousFocus=document.activeElement;el._trap=e=>{if(e.key!=='Tab')return;const controls=[...el.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')].filter(n=>n.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};el.addEventListener('keydown',el._trap);el.querySelector('input:not(:disabled),select:not(:disabled),button:not(:disabled)')?.focus()},unmounted(el){el.removeEventListener('keydown',el._trap);el._previousFocus?.focus()}};
const user=ref(null),csrf=ref(''),login=ref({username:'',password:''}),recentLogins=ref(loadRecentLogins()),passwordInput=ref(null),error=ref(''),busy=ref(false),notice=ref('');
const loginSuggestions=computed(()=>matchingLogins(recentLogins.value,login.value.username));
const page=ref(location.hash.slice(1)||'home'),currency=ref('UZS'),days=ref(30),year=ref(new Date().getFullYear()),month=ref(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tashkent'}).slice(0,7));
const boot=ref({accounts:[],categories:[],roles:{}}),rows=ref([]),dash=ref(null),report=ref(null),preview=ref(null),settings=ref(null),search=ref(''),modal=ref(null),form=ref({}),formError=ref(''),saving=ref(false),documents=ref(null);
const allNav=[['home','◈','Обзор','view'],['accounts','▣','Банк и касса','view'],['ledger','⇄','Операции','ledger'],['requests','✓','Заявки','requests-view'],['calendar','▦','Календарь','view'],['budgets','◷','Бюджеты','view'],['import','↥','Импорт данных','import'],['report','▥','Отчёт Cash Flow','export'],['categories','≡','Справочники','catalog'],['users','♙','Пользователи','users'],['audit','⊞','Журнал действий','audit'],['schedules','✉','Рассылка','users'],['profile','⚙','Мой профиль','']];
const has=p=>p==='requests-view'?(user.value?.permissions.includes('request')||user.value?.permissions.includes('view')):user.value?.permissions.includes(p), nav=computed(()=>allNav.filter(n=>!n[3]||has(n[3]))), title=computed(()=>allNav.find(n=>n[0]===page.value)?.[2]||'Казначейство');
const status={pending:'На согласовании',approved:'Утверждена',paid:'Оплачена',draft:'Черновик',rejected:'Отклонена',returned:'На доработке',cancelled:'Отменена',expected:'Ожидается',received:'Получено'};
const money=v=>v==null?'—':String(v).replace(/\B(?=(\d{3})+(?!\d))/g,' ');
const amountFields=['amount','opening','limit','spent','reserved','remaining','balance'];
const visibleRows=computed(()=>rows.value.filter(r=>(!r.currency||r.currency===currency.value)&&JSON.stringify(r).toLowerCase().includes(search.value.toLowerCase())));
const otherCurrencies=computed(()=>[...new Set(boot.value.accounts.map(a=>a.currency))].filter(c=>c!==currency.value));
const currentAccounts=computed(()=>boot.value.accounts.filter(a=>a.currency===currency.value));
const modalFields=computed(()=>{const fields=modal.value?.fields||[];if(fields.some(f=>f.key==='action'))return fields.filter(f=>f.key!=='date'||form.value.action==='reschedule');if(!fields.some(f=>f.key==='to_account_id'))return fields;return fields.filter(f=>f.key==='to_account_id'?form.value.kind==='transfer':f.key==='category_id'?form.value.kind!=='transfer':true)});
const categoryHint=computed(()=>{if(!modal.value?.fields.some(f=>f.key==='to_account_id')||form.value.kind==='transfer')return '';const c=boot.value.categories.find(c=>c.id===Number(form.value.category_id));return c&&c.type!==(form.value.kind==='in'?'income':'outcome')?'Проверьте статью: её тип не совпадает с направлением операции. Если это возврат, укажите пояснение в комментарии.':''});
async function switchCurrency(value){currency.value=value;search.value='';await load()}
const subtitles={accounts:'Начальные остатки и движение денег по каждому счёту.',ledger:'Фактическое движение денег по вашим счетам.',schedules:'Финансовые отчёты по расписанию · время Ташкента.'};
const priorities={normal:'Обычный',high:'Высокий',urgent:'Срочный'};
const scenario=ref('approved');
const forecastRows=computed(()=>(dash.value?.forecast||[]).map(d=>scenario.value==='all'?{...d,opening:d.requested_opening,outgoing:d.requested_outgoing,balance:d.requested_balance,risk:d.requested_risk,account_shortfalls:d.requested_account_shortfalls,events:[...d.events,...d.pending_events]}:d));
const canEditRequest=r=>has('request')&&['draft','pending','returned','rejected'].includes(r.status)&&(r.creator_id===user.value.id||user.value.role==='admin');
const risk=computed(()=>dash.value?.forecast.find(d=>d.risk));
const chartPoints=computed(()=>{let a=dash.value?.forecast.map(d=>Number(d.balance))||[];let lo=Math.min(...a,0),hi=Math.max(...a,1);return a.map((v,i)=>`${20+i*860/(a.length-1||1)},${190-(v-lo)*160/(hi-lo||1)}`).join(' ')});
async function api(url,opts={}){const r=await fetch(url,{credentials:'same-origin',...opts,headers:{'X-CSRF-Token':csrf.value,...opts.headers}});let data;try{data=await r.json()}catch{throw Error('Некорректный ответ сервера')}if(!r.ok){if(r.status===401)user.value=null;throw Error(Array.isArray(data.detail)?data.detail.map(x=>`${x.loc?.slice(1).join('.')}: ${x.msg}`).join('; '):data.detail||'Ошибка запроса')}return data}
const post=(url,data={})=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function flash(text){notice.value=text;setTimeout(()=>notice.value='',5500)}
async function bootstrap(){boot.value=await api('/api/bootstrap');user.value=boot.value.user;csrf.value=boot.value.csrf;month.value=month.value.match(/^\d{4}-\d{2}$/)?month.value:boot.value.today.slice(0,7)}
async function enter(){await bootstrap();if(!nav.value.some(n=>n[0]===page.value))page.value=nav.value[0][0];await load()}
async function chooseRecentLogin(username){login.value.username=username;login.value.password='';error.value='';await nextTick();passwordInput.value?.focus()}
async function signIn(event){
 if(busy.value)return;
 // Read the submitted fields directly, including browser autofill without input events.
 const fields=new FormData(event.currentTarget);
 const credentials={username:String(fields.get('username')||'').trim(),password:String(fields.get('password')||'')};
 busy.value=true;error.value='';
 try{
  const r=await post('/api/login',credentials);
  recentLogins.value=rememberLogin(r.user.username||credentials.username,recentLogins.value);
  offerPasswordSave(credentials);
  csrf.value=r.csrf;user.value=r.user;
  // Removing the submitted form lets native password managers detect success.
  await nextTick();login.value.password='';
  await enter();
 }catch(e){error.value=e.message}finally{busy.value=false}
}
async function logout(){try{await post('/api/logout')}finally{user.value=null;csrf.value=''}}
async function go(name){page.value=name;location.hash=name;search.value='';rows.value=[];await load()}
async function load(){busy.value=true;error.value='';try{
 if(['home','calendar'].includes(page.value))dash.value=await api(`/api/dashboard?currency=${currency.value}&days=${days.value}`);
 if(page.value==='accounts')rows.value=await api('/api/accounts');
 if(page.value==='ledger')rows.value=await api('/api/ledger');
 if(page.value==='requests')rows.value=await api('/api/requests');
 if(page.value==='budgets')rows.value=await api(`/api/budgets?currency=${currency.value}&month=${month.value}`);
 if(page.value==='report')report.value=await api(`/api/report?currency=${currency.value}&year=${year.value}`);
 if(page.value==='categories')rows.value=boot.value.categories;
 if(page.value==='users')rows.value=await api('/api/users');
 if(page.value==='audit')rows.value=await api('/api/audit');
 if(page.value==='schedules')settings.value=await api('/api/report-schedules');
 }catch(e){error.value=e.message}finally{busy.value=false}}
const field=(key,label,type='text',extra={})=>({key,label,type,required:true,...extra});
const accounts=()=>boot.value.accounts.map(a=>[a.id,`${a.name} · ${a.currency}`]);
const categories=()=>boot.value.categories.map(c=>[c.id,`${c.name} · ${c.type==='income'?'приход':'расход'}`]);
function open(title,fields,values,submit,note=''){form.value={...values};formError.value='';modal.value={title,fields,submit,note}}
async function save(){saving.value=true;formError.value='';try{await modal.value.submit({...form.value});modal.value=null;await bootstrap();await load();flash('Сохранено')}catch(e){formError.value=e.message}finally{saving.value=false}}
function account(a=null){open(a?'Редактировать счёт':'Добавить счёт',[
 field('name','Название'),field('kind','Тип','select',{options:[['bank','Банковский счёт'],['cash','Касса']]}),field('currency','Валюта','select',{options:['UZS','USD','EUR'].map(x=>[x,x])}),field('opening','Начальный остаток','number',{min:0}),field('opening_date','Дата начала учёта','date'),field('allow_overdraft','Разрешён овердрафт','checkbox',{required:false}),...(a?[field('reason','Причина исправления','textarea',{minlength:10})]:[])],a||{name:'',kind:'bank',currency:currency.value,opening:'0',opening_date:boot.value.today,allow_overdraft:false},d=>post(a?`/api/accounts/${a.id}`:'/api/accounts',Object.fromEntries(['name','kind','currency','opening','opening_date','allow_overdraft',...(a?['reason']:[])].map(k=>[k,k==='opening'?String(d[k]):d[k]]))),'Остаток на начало дня. Изменения сохраняются в журнале. Валюта счёта с историей защищена от изменения.')}
function transaction(link=null,receipt=false){if(!link&&!currentAccounts.value.length){go('accounts');return}open(link?'Подтвердить факт':'Новая операция',[
 field('kind','Тип','select',{options:[['in','Поступление'],['out','Расход'],['transfer','Внутренний перевод']],disabled:!!link}),field('account_id','Счёт','select',{options:accounts(),disabled:!!link}),field('to_account_id','Счёт-получатель (для перевода)','select',{options:[[null,'—'],...accounts()],required:false}),field('category_id','Статья','select',{options:categories(),disabled:!!link}),field('amount','Сумма','number',{min:.01,disabled:!!link}),field('date','Дата факта','date'),field('reference','Номер документа'),field('counterparty','Контрагент','text',{required:false}),field('note','Основание / комментарий','textarea',{required:false})],{kind:link?(receipt?'in':'out'):'in',account_id:link?.account_id||currentAccounts.value[0]?.id,to_account_id:null,category_id:link?.category_id||boot.value.categories[0]?.id,amount:link?.amount||'',date:boot.value.today,reference:'',counterparty:link?.counterparty||'',note:link?.purpose||''},d=>post('/api/ledger',{...d,amount:String(d.amount),category_id:d.kind==='transfer'?null:Number(d.category_id),account_id:Number(d.account_id),to_account_id:d.kind==='transfer'?Number(d.to_account_id):null,request_id:link&&!receipt?link.id:null,request_version:link&&!receipt?link.version:null,receipt_id:link&&receipt?link.id:null}),'Записывайте только фактически совершённые операции. Для расхода без заявки основание — от 10 символов.')}
function requestForm(r=null){
 const fields=[field('account_id','Счёт списания','select',{options:accounts()}),field('category_id','Статья','select',{options:categories()}),field('amount','Сумма','number',{min:.01}),field('date','Плановая дата','date'),field('counterparty','Контрагент'),field('purpose','Назначение','textarea',{minlength:5}),field('priority','Приоритет','select',{options:Object.entries(priorities)}),field('status','После сохранения','select',{options:[['pending','Отправить на согласование'],['draft','Сохранить черновик']]}),...(r?[field('reason','Причина изменения','textarea',{minlength:10})]:[])];
 const values=r?{account_id:r.account_id,category_id:r.category_id,amount:r.amount,date:r.date,counterparty:r.counterparty,purpose:r.purpose,priority:r.priority,project:r.project,status:'draft',reason:''}:{account_id:currentAccounts.value[0]?.id,category_id:boot.value.categories.find(c=>c.type==='outcome')?.id,amount:'',date:boot.value.today,counterparty:'',purpose:'',priority:'normal',status:'pending'};
 open(r?'Изменить '+r.number:'Новая заявка',fields,values,d=>r?api(`/api/requests/${r.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,amount:String(d.amount),version:r.version})}):post('/api/requests',{...d,amount:String(d.amount)}),'Автор и последний редактор не могут утвердить заявку. Согласование выполняет другой пользователь.');
}
function requestActions(r){const options=[];
 if(has('approve')&&r.status==='pending'&&![r.creator_id,r.last_editor_id].includes(user.value.id))options.push(['approve','Утвердить'],['reject','Отклонить']);
 if(has('approve')&&['pending','approved'].includes(r.status))options.push(['return','Вернуть на доработку'],['reschedule','Перенести дату']);
 if(has('request')&&(r.creator_id===user.value.id||['admin','finance'].includes(user.value.role))&&['draft','pending','approved','returned','rejected'].includes(r.status))options.push(['cancel','Отменить заявку']);
 return options;
}
function decision(r){const options=requestActions(r);open('Действие · '+r.number,[field('action','Действие','select',{options}),field('date','Новая дата (при переносе)','date',{required:false}),field('note','Обоснование','textarea',{minlength:10})],{action:options[0][0],date:r.date,note:''},d=>post(`/api/requests/${r.id}/decision`,{...d,version:r.version}),'Возврат, перенос и отмена освобождают резерв бюджета. При переносе требуется повторное согласование.')}
async function submitRequest(r){try{await post(`/api/requests/${r.id}/decision`,{action:'submit',version:r.version});await load()}catch(e){error.value=e.message}}
function budget(r){open('Бюджет · '+r.category,[field('amount','Лимит','number',{min:0}),field('mode','Контроль','select',{options:[['soft','Мягкий: требуется обоснование'],['hard','Жёсткий: запрет превышения']]}),field('reason','Причина / основание','textarea',{minlength:10})],{amount:r.limit||'0',mode:r.mode,reason:''},d=>post('/api/budgets',{...d,amount:String(d.amount),category_id:r.category_id,month:month.value,currency:currency.value}))}
function category(c=null){open(c?'Редактировать статью':'Новая статья',[field('name','Название'),field('type','Тип','select',{options:[['income','Доход'],['outcome','Расход']]}),field('activity','Деятельность','select',{options:[['operating','Операционная'],['investing','Инвестиционная'],['financing','Финансовая']]})],c?{name:c.name,type:c.type,activity:c.activity}:{name:'',type:'outcome',activity:'operating'},d=>c?api(`/api/categories/${c.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}):post('/api/categories',d))}
function editUser(u=null){open(u?'Доступ · '+u.name:'Новый пользователь',[...(!u?[field('username','Логин'),field('name','Имя')]:[]),field('role','Роль','select',{options:Object.entries(boot.value.roles)}),field('password',u?'Новый пароль (необязательно)':'Пароль','password',{required:!u,minlength:12}),...(u?[field('active','Активен','checkbox',{required:false})]:[])],u?{role:u.role,active:u.active,password:''}:{username:'',name:'',role:'accountant',password:''},d=>post(u?`/api/users/${u.id}`:'/api/users',d))}
function reverse(r){open('Сторно операции '+r.reference,[field('reason','Причина сторно','textarea',{minlength:10})],{reason:''},d=>post(`/api/ledger/${r.id}/reverse`,d),'Исправление отменит влияние ошибочной операции. История останется в журнале.')}
function changePassword(){open('Смена пароля',[field('old_password','Текущий пароль','password'),field('new_password','Новый пароль','password',{minlength:12})],{old_password:'',new_password:''},async d=>{await post('/api/password',d);user.value=null;location.reload()})}
function receipt(){open('Ожидаемое поступление',[field('account_id','Счёт','select',{options:accounts()}),field('category_id','Статья','select',{options:categories()}),field('amount','Сумма','number',{min:.01}),field('date','Ожидаемая дата','date'),field('counterparty','Контрагент')],{account_id:boot.value.accounts[0]?.id,category_id:boot.value.categories.find(c=>c.type==='income')?.id,amount:'',date:boot.value.today,counterparty:''},d=>post('/api/receipts',{...d,amount:String(d.amount)}))}
const receipts=ref([]);
async function showReceipts(){try{receipts.value=(await api('/api/receipts')).filter(r=>r.currency===currency.value&&r.status==='expected')}catch(e){error.value=e.message}}
async function upload(event){const file=event.target.files[0];if(!file)return;busy.value=true;error.value='';preview.value=null;try{preview.value=await api('/api/import/preview',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name)},body:file})}catch(e){error.value=e.message}finally{busy.value=false;event.target.value=''}}
async function googlePreview(){busy.value=true;error.value='';preview.value=null;try{preview.value=await post('/api/import/google-preview')}catch(e){error.value=e.message}finally{busy.value=false}}
async function commit(){busy.value=true;try{const r=await post(`/api/import/${preview.value.id}/commit`);preview.value=null;flash(`Импортировано операций: ${r.count}`);await bootstrap()}catch(e){error.value=e.message}finally{busy.value=false}}
async function docs(r){try{documents.value={ledger:r,rows:await api(`/api/documents?ledger_id=${r.id}`)}}catch(e){error.value=e.message}}
async function attach(event){const file=event.target.files[0];if(!file)return;saving.value=true;try{await api(`/api/ledger/${documents.value.ledger.id}/document`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name)},body:file});await docs(documents.value.ledger)}catch(e){error.value=e.message}finally{saving.value=false;event.target.value=''}}
function schedule(r=null){open('Ежедневная рассылка',[field('recipient','Email получателя','email'),field('currency','Валюта','select',{options:['UZS','USD','EUR'].map(x=>[x,x])}),field('hour','Час отправки · Ташкент','number',{min:0,max:23,step:1}),field('enabled',settings.value?.smtp_configured?'Включить отправку':'Отправка недоступна до подключения почты','checkbox',{required:false,disabled:!settings.value?.smtp_configured})],r?{recipient:r.recipient,currency:r.currency,hour:r.hour,enabled:r.enabled&&settings.value?.smtp_configured}:{recipient:'',currency:currency.value,hour:9,enabled:false},d=>r?api(`/api/report-schedules/${r.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,hour:Number(d.hour)})}):post('/api/report-schedules',{...d,hour:Number(d.hour)}),settings.value?.smtp_configured?'Ежедневный отчёт за текущий год в XLSX и PDF. Время отправки — Ташкент (UTC+5).':'Почта отправителя ещё не подключена. Сохраните расписание как черновик — письма отправляться не будут.');modal.value.saveLabel=!settings.value?.smtp_configured?'Сохранить черновик':'Сохранить'}
async function removeSchedule(r){try{await api(`/api/report-schedules/${r.id}`,{method:'DELETE'});await load()}catch(e){error.value=e.message}}
async function reserve(){open('Минимальный резерв',[field('amount','Сумма резерва','number',{min:0})],{amount:dash.value?.reserve||'0'},d=>post('/api/reserve',{amount:String(d.amount),currency:currency.value}))}
window.addEventListener('hashchange',()=>{const target=location.hash.slice(1);if(user.value&&target!==page.value&&nav.value.some(n=>n[0]===target)){page.value=target;load()}});
onMounted(async()=>{try{const r=await api('/api/me');user.value=r.user;csrf.value=r.csrf;await enter()}catch{user.value=null}});
</script>

<template>
 <div v-if="availableRelease" class="release-notice" role="status"><span>Доступна версия {{availableRelease.version}}. Сохраните текущие изменения перед обновлением.</span><button class="secondary" @click="refreshVersion">Обновить страницу</button></div>
 <button class="release-badge" @click="showRelease=true" :aria-expanded="showRelease">Версия {{release.version}} · Что нового</button>
 <div v-if="showRelease" class="modal-backdrop" @click.self="showRelease=false" @keydown.esc="showRelease=false"><section class="modal release-dialog" role="dialog" aria-modal="true" aria-labelledby="release-title" v-modal-focus><div class="section-head"><h2 id="release-title">Что нового · {{release.version}}</h2><button class="ghost" aria-label="Закрыть список изменений" @click="showRelease=false">×</button></div><p>{{release.date}}</p><ul><li v-for="change in release.changes" :key="change">{{change}}</li></ul></section></div>
 <div v-if="!user" class="login-layout">
  <section class="login-art"><div class="brand"><span>U</span><div>UZGERMED<small>FINANCE WORKSPACE</small></div></div><div><p class="eyebrow">МИНИ-ERP · КАЗНАЧЕЙСТВО</p><h1>Деньги под контролем.<br><em>Решения — вовремя.</em></h1><p>Счета, платежи и бюджеты.<br>Одно пространство для финансовой команды.</p><div class="login-lines"><span>БАНК</span><span>КАССА</span><span>CASH FLOW</span><svg viewBox="0 0 500 130"><polyline points="0,120 60,100 110,108 170,62 220,80 280,40 340,55 400,10 450,28 500,4" fill="none" stroke="#8adbc5" stroke-width="3"/></svg></div></div><small>Закрытая корпоративная система</small></section>
  <form id="login-form" class="login-form" method="post" action="/api/login" autocomplete="on" @submit.prevent="signIn">
   <p class="eyebrow">UZGERMED TREASURY</p><h2>Добро пожаловать</h2><p>Войдите в финансовое пространство компании.</p>
   <label for="username">Логин
    <input id="username" v-model="login.username" name="username" type="text" list="recent-logins" autocomplete="username" autocapitalize="none" :spellcheck="false" aria-describedby="login-hint" placeholder="Введите логин" required :readonly="busy">
    <datalist id="recent-logins"><option v-for="name in recentLogins" :key="name" :value="name" /></datalist>
   </label>
   <div v-if="loginSuggestions.length" class="recent-logins" role="group" aria-label="Последние логины">
    <span>Последние логины</span>
    <button v-for="name in loginSuggestions" :key="name" type="button" class="recent-login" :disabled="busy" @click="chooseRecentLogin(name)">{{name}}</button>
   </div>
   <small id="login-hint" class="login-hint">Здесь появятся 3 последних успешных логина из этого браузера.</small>
   <label for="current-password">Пароль<input id="current-password" ref="passwordInput" v-model="login.password" name="password" type="password" autocomplete="current-password" aria-describedby="password-hint" placeholder="Введите пароль" required :readonly="busy"></label>
   <p v-if="error" class="error" role="alert">{{error}}</p>
   <button type="submit" :disabled="busy">{{busy?'Входим…':'Войти в систему →'}}</button>
   <small id="password-hint">Для автозаполнения пароля подтвердите «Сохранить» в предложении браузера. Доступность зависит от браузера и его настроек.</small>
  </form>
 </div>
 <div v-else class="layout"><aside><div class="brand"><span>U</span><div>UZGERMED<small>МИНИ-ERP КАЗНАЧЕЙСТВО</small></div></div><p class="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</p><nav><button v-for="n in nav" :key="n[0]" :class="{active:page===n[0]}" @click="go(n[0])"><AppIcon :name="n[0]"/>{{n[2]}}</button></nav><div class="identity"><b>{{user.name}}</b><small>{{user.role_label}}</small><button class="ghost" @click="logout">Выйти ↗</button></div></aside><main><header><div><p class="eyebrow">UZGERMED / ФИНАНСЫ</p><h1>{{title}}</h1><p v-if="subtitles[page]" class="page-description">{{subtitles[page]}}</p></div><div class="header-actions"><select v-model="currency" @change="load" aria-label="Валюта учёта"><option>UZS</option><option>USD</option><option>EUR</option></select><button class="secondary" @click="load">↻ Обновить</button></div></header><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><div v-if="busy" class="loading">Загрузка данных…</div>
 <template v-if="page==='home'&&dash"><div class="hero-grid"><section class="hero"><p>ДЕНЕЖНЫЕ СРЕДСТВА СЕЙЧАС</p><h2>{{money(dash.balance)}} <small>{{currency}}</small></h2><span>{{dash.as_of}} · {{dash.account_count}} счетов · Фактический остаток</span><footer>Минимальный резерв: {{money(dash.reserve)}} {{currency}} <button v-if="has('budget')" class="ghost" @click="reserve">Изменить</button></footer></section><section class="card review"><p class="eyebrow">ТРЕБУЮТ РЕШЕНИЯ</p><h2>{{dash.pending_count}} <small>заявок</small></h2><p>На сумму {{money(dash.pending_amount)}} {{currency}}</p><button v-if="has('request')" class="secondary" @click="go('requests')">Открыть заявки →</button></section></div><div class="metrics"><section v-for="m in [['План прихода · следующие 7 дней',dash.incoming7],['План оплат · следующие 7 дней',dash.outgoing7],['Приход · текущий месяц',dash.fact_in],['Расход · текущий месяц',dash.fact_out]]" class="card"><p>{{m[0]}}</p><h3>{{money(m[1])}} <small>{{currency}}</small></h3></section></div><section v-if="risk" class="warning"><b>Проверьте ликвидность на {{risk.date}}</b><p v-if="risk.reserve_risk">Общий остаток ниже резерва: {{money(risk.balance)}} {{currency}}</p><p v-for="a in risk.account_shortfalls">{{a.account}}: {{money(a.balance)}} {{currency}}</p></section><section class="card"><div class="section-head"><h3>Прогноз денежных средств</h3><select v-model="days" @change="load"><option :value="7">7 дней</option><option :value="30">30 дней</option><option :value="90">90 дней</option></select></div><p v-if="dash.balance===null" class="empty">Добавьте начальные остатки счетов для расчёта прогноза.</p><svg v-else class="chart" viewBox="0 0 900 220" aria-label="Прогноз остатка"><path d="M20 190H880 M20 110H880 M20 30H880" stroke="#e4ebe9"/><polyline :points="chartPoints" fill="none" stroke="#168875" stroke-width="3"/></svg><div class="chart-labels"><span>{{dash.forecast[0]?.date}}</span><span>{{dash.forecast.at(-1)?.date}}</span></div><p class="muted">{{dash.note}}</p></section></template>
 <template v-if="page==='accounts'"><div class="toolbar"><span class="badge">Счета: {{visibleRows.length}} · {{currency}}</span><button v-if="has('write')" @click="account()">+ Добавить счёт</button></div><div class="accounts"><section v-for="a in visibleRows" class="card account"><div class="section-head"><span class="symbol"><AppIcon :name="a.kind==='bank'?'accounts':'cash'"/></span><span class="badge">{{a.currency}}</span></div><h3>{{a.name}}</h3><p>{{a.kind==='bank'?'Банковский счёт':'Касса'}}</p><p class="balance-label">ТЕКУЩИЙ ОСТАТОК</p><h2>{{money(a.balance)}}<small>{{a.currency}}</small></h2><p class="opening-balance">На начало {{a.opening_date}}<br><strong>{{money(a.opening)}} {{a.currency}}</strong></p><button v-if="has('write')" class="secondary" @click="account(a)">Редактировать</button></section></div><section v-if="!visibleRows.length&&!busy" class="empty-state card"><div class="empty-icon" aria-hidden="true">▣</div><h2>Добавьте первый счёт в {{currency}}</h2><p>Укажите банк или кассу и начальный остаток.<br>Дальше баланс будет рассчитываться по операциям.</p><div class="actions"><button v-if="has('write')" @click="account()">+ Добавить счёт</button><button v-for="c in otherCurrencies" class="secondary" @click="switchCurrency(c)">Показать {{c}}</button></div><small>Остаток можно исправить позже. Изменения попадут в журнал.</small></section></template>
 <template v-if="page==='ledger'"><div class="toolbar"><input v-model="search" class="search-input" placeholder="Поиск операции" aria-label="Поиск операции"><div><a v-if="has('export')" class="button secondary" href="/api/export/ledger.csv">Скачать CSV</a> <button v-if="has('write')" @click="transaction()">+ Новая операция</button></div></div><div class="table-card"><table><thead><tr><th>Дата / документ</th><th>Счёт / контрагент</th><th>Статья</th><th>Тип</th><th class="num">Сумма</th><th>Документы</th><th></th></tr></thead><tbody><tr v-for="r in visibleRows"><td>{{r.date}}<small>{{r.reference}}</small></td><td>{{r.account}}<small>{{r.counterparty}}</small></td><td>{{r.category}}</td><td>{{{in:'Приход',out:'Расход',transfer:'Перевод'}[r.kind]}}<small v-if="r.reversed||r.reversal_of">Сторно</small></td><td class="num">{{money(r.amount)}} {{r.currency}}</td><td><button class="secondary tiny" @click="docs(r)">Документы</button></td><td><button v-if="has('budget')&&!r.reversed&&!r.reversal_of" class="ghost" @click="reverse(r)">Сторно</button></td></tr></tbody></table><section v-if="!visibleRows.length&&!busy" class="empty-state"><div class="empty-icon" aria-hidden="true">⇄</div><h2>{{search?'Ничего не найдено':'Пока нет операций в '+currency}}</h2><p>{{search?'Попробуйте другой запрос или сбросьте поиск.':currentAccounts.length?'Добавьте поступление, расход или перевод между счетами.':'Сначала добавьте счёт в этой валюте и укажите начальный остаток.'}}</p><div class="actions"><button v-if="search" class="secondary" @click="search=''">Сбросить поиск</button><button v-else-if="has('write')" @click="currentAccounts.length?transaction():go('accounts')">{{currentAccounts.length?'+ Новая операция':'Перейти к счетам'}}</button><button v-if="!search" v-for="c in otherCurrencies" class="secondary" @click="switchCurrency(c)">Показать {{c}}</button></div><small>Выбрана {{currency}}. Операции в других валютах учитываются отдельно.</small></section></div><p class="muted">Показано: {{visibleRows.length}} · Последние 500 операций. CSV содержит полный реестр во всех валютах.</p></template>
 <template v-if="page==='requests'"><div class="toolbar"><input v-model="search" placeholder="Поиск заявки"><button v-if="has('request')" @click="requestForm()">+ Создать заявку</button></div><div class="accounts"><section v-for="r in visibleRows" class="card"><div class="section-head"><span>{{r.number}}</span><span class="badge">{{status[r.status]}}</span></div><h3>{{r.counterparty}}</h3><p>{{r.purpose}}</p><h2>{{money(r.amount)}} <small>{{r.currency}}</small></h2><p>{{r.date}} · {{r.account}} · {{priorities[r.priority]}}</p><p v-if="r.decision_note" class="muted">{{r.decision_note}}</p><p v-if="r.budget.limit!=null" class="muted">Доступно по бюджету: {{money(r.budget.remaining)}} {{r.currency}}</p><div class="actions"><button v-if="canEditRequest(r)" class="secondary" @click="requestForm(r)">Изменить</button><button v-if="['draft','returned'].includes(r.status)&&canEditRequest(r)" @click="submitRequest(r)">Отправить</button><button v-if="requestActions(r).length" class="secondary" @click="decision(r)">Действия</button><button v-if="r.status==='approved'&&has('write')" @click="transaction(r)">Факт оплаты</button></div></section></div><p v-if="!visibleRows.length" class="empty">Заявок в выбранной валюте нет.</p></template>
 <template v-if="page==='calendar'&&dash"><div class="toolbar"><label>Сценарий <select v-model="scenario"><option value="approved">Утверждённые оплаты</option><option value="all">Все заявки, включая согласование</option></select></label><select v-model="days" @change="load"><option :value="7">7 дней</option><option :value="30">30 дней</option><option :value="90">90 дней</option></select><div><button class="secondary" @click="showReceipts">Ожидаемые поступления</button> <button v-if="has('schedule')" @click="receipt">+ План поступления</button></div></div><div v-for="r in receipts" class="card compact"><span>{{r.counterparty}} · {{money(r.amount)}} {{r.currency}} · {{r.date}}</span><button v-if="has('write')" @click="transaction(r,true)">Подтвердить приход</button></div><div class="table-card"><table><thead><tr><th>Дата</th><th>События</th><th class="num">На начало дня</th><th class="num">Поступления</th><th class="num">Платежи</th><th class="num">Остаток</th></tr></thead><tbody><tr v-for="d in forecastRows" :class="{danger:d.risk}"><td>{{d.date}}</td><td><div v-for="e in d.events">{{e.kind==='in'?'↓':e.kind==='pending'?'◌':'↑'}} {{e.name}} {{e.kind==='pending'?'· на согласовании':''}} {{e.priority&&e.priority!=='normal'?'· '+priorities[e.priority]:''}} {{e.overdue?'· просрочка':''}}</div></td><td class="num">{{money(d.opening)}}</td><td class="num">{{money(d.incoming)}}</td><td class="num">{{money(d.outgoing)}}</td><td class="num">{{money(d.balance)}}<small v-for="a in d.account_shortfalls">{{a.account}}: {{money(a.balance)}}</small></td></tr></tbody></table></div><p class="muted">{{dash.scenario_note}}</p><p class="muted">{{dash.note}}</p></template>
 <template v-if="page==='budgets'"><div class="toolbar"><input v-model="month" type="month" @change="load"><p>Использовано = оплачено + утверждено, но не оплачено</p></div><div class="table-card"><table><thead><tr><th>Статья</th><th class="num">Лимит</th><th class="num">Оплачено</th><th class="num">Резерв</th><th class="num">Остаток</th><th>Контроль</th><th></th></tr></thead><tbody><tr v-for="r in rows"><td>{{r.category}}</td><td class="num">{{money(r.limit)}}</td><td class="num">{{money(r.spent)}}</td><td class="num">{{money(r.reserved)}}</td><td class="num" :class="{negative:Number(r.remaining)<0}">{{money(r.remaining)}}</td><td>{{r.mode==='hard'?'Жёсткий':'Мягкий'}}</td><td><button v-if="has('budget')" class="secondary tiny" @click="budget(r)">Изменить</button></td></tr></tbody></table></div></template>
 <template v-if="page==='import'"><section class="card"><p class="eyebrow">01 / ЗАГРУЗКА → 02 / ПРОВЕРКА → 03 / ПОДТВЕРЖДЕНИЕ</p><h2>Импорт реестра операций</h2><p>CSV в UTF-8 или XLSX, до 5 МБ и 1000 операций. Импорт применяет те же проверки, что и ручной ввод.</p><div class="actions"><a class="button secondary" href="/api/import/template.csv">Скачать шаблон CSV</a><label class="button">Выбрать файл<input type="file" accept=".csv,.xlsx" @change="upload" :disabled="busy" hidden></label><button class="secondary" @click="googlePreview" :disabled="busy">Загрузить из Google Sheets</button></div><details><summary>Справочные ID для заполнения шаблона</summary><p v-for="a in boot.accounts">Счёт {{a.id}} — {{a.name}} ({{a.currency}})</p><p v-for="c in boot.categories">Статья {{c.id}} — {{c.name}}</p><p>kind: in / out / transfer. date: ГГГГ-ММ-ДД. amount: сумма с точкой. reference: уникальный номер документа на счёте. Для расхода note — от 10 символов. Лист XLSX должен быть первым.</p></details></section><section v-if="preview" class="card"><h3>Проверено строк: {{preview.count}}</h3><p v-for="e in preview.errors" class="error">Строка {{e.line}}: {{e.error}}</p><div class="table-scroll"><table><thead><tr><th>Дата</th><th>Документ</th><th>Контрагент</th><th>Сумма</th></tr></thead><tbody><tr v-for="r in preview.rows"><td>{{r.date}}</td><td>{{r.reference}}</td><td>{{r.counterparty}}</td><td>{{money(r.amount)}}</td></tr></tbody></table></div><button v-if="preview.can_commit" @click="commit" :disabled="busy">Подтвердить импорт {{preview.rows.length}} операций</button><p v-else>Исправьте ошибки в исходном файле и загрузите его снова. Операции не записаны.</p></section><section class="card"><h3>Историческая FinModel</h3><p>Импорт реестра создаёт операции. Историческая модель хранится отдельно и не меняет остатки.</p><a class="button secondary" href="/legacy#model" target="_blank" rel="noopener">Открыть FinModel ↗</a></section></template>
 <template v-if="page==='report'&&report"><div class="toolbar"><input v-model="year" aria-label="Год отчёта" type="number" min="2000" max="2100" @change="load"><div><a class="button secondary" :href="`/api/export/report.xlsx?year=${year}&currency=${currency}`">Скачать XLSX</a> <a class="button" :href="`/api/export/report.pdf?year=${year}&currency=${currency}`">Скачать PDF</a></div></div><p class="muted">Суммы в {{currency}} · Плюс — поступление, минус — выплата. Прокрутите таблицу вправо к нужному месяцу.</p><div class="table-card cashflow-table" tabindex="0" role="region" aria-label="Движение денежных средств по месяцам"><table><thead><tr><th>Статья</th><th v-for="m in ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек']" class="num">{{m}}</th></tr></thead><tbody><tr v-for="r in report.rows"><td>{{r.category}}</td><td v-for="v in r.values" class="num">{{money(v)}}</td></tr><tr class="total"><td>Чистый поток</td><td v-for="v in report.totals" class="num">{{money(v)}}</td></tr></tbody></table></div><p class="muted">{{report.note}}</p></template>
 <template v-if="page==='categories'"><div class="toolbar"><p>Статьи доходов и расходов</p><button @click="category()">+ Добавить статью</button></div><div class="table-card"><table><thead><tr><th>ID</th><th>Название</th><th>Тип</th><th>Деятельность</th><th></th></tr></thead><tbody><tr v-for="r in rows"><td>{{r.id}}</td><td>{{r.name}}</td><td>{{r.type==='income'?'Доход':'Расход'}}</td><td>{{{operating:'Операционная',investing:'Инвестиционная',financing:'Финансовая'}[r.activity]}}</td><td><button class="secondary tiny" @click="category(r)">Изменить</button></td></tr></tbody></table></div></template>
 <template v-if="page==='users'"><div class="toolbar"><p>Права проверяются сервером при каждом запросе.</p><button @click="editUser()">+ Пользователь</button></div><div class="table-card"><table><thead><tr><th>Имя</th><th>Логин</th><th>Роль</th><th>Статус</th><th></th></tr></thead><tbody><tr v-for="r in rows"><td>{{r.name}}</td><td>{{r.username}}</td><td>{{r.role_label}}</td><td>{{r.active?'Активен':'Отключён'}}</td><td><button class="secondary tiny" @click="editUser(r)">Управлять</button></td></tr></tbody></table></div></template>
 <template v-if="page==='audit'"><p class="muted">Последние 200 событий, включая чтение API. Пароли и токены не записываются.</p><div class="table-card"><table><thead><tr><th>Время</th><th>Пользователь</th><th>Действие</th><th>Подробности</th></tr></thead><tbody><tr v-for="r in rows"><td>{{r.date}}</td><td>{{r.user}}</td><td>{{r.action}}</td><td class="wrap">{{r.detail}}</td></tr></tbody></table></div></template>
 <template v-if="page==='schedules'&&settings"><section class="connection-card card"><div class="connection-icon" aria-hidden="true">✉</div><div><span class="badge">{{settings.smtp_configured?'Настройки отправителя сохранены':'Требуется подключение'}}</span><h3>{{settings.smtp_configured?'Почта отправителя настроена':'Подключите почту отправителя'}}</h3><p>{{settings.smtp_configured?'Рассылку выполняет сервер по включённым расписаниям.':'Чтобы отправлять отчёты, укажите почту и параметры подключения на сервере. Пока можно сохранять черновики.'}}</p><details v-if="!settings.smtp_configured"><summary>Что нужно для подключения</summary><p>Адрес отправителя, SMTP-сервер, порт и пароль приложения почтового сервиса. Администратор указывает их в защищённой конфигурации сервера и перезапускает приложение. После подключения включите нужное расписание.</p><p>Пароль не нужно указывать в адресе получателя или отправлять в чат.</p></details></div></section><section class="card"><div class="section-head"><div><h3>Ежедневные отчёты</h3><p class="section-description">XLSX и PDF · текущий год · Ташкент (UTC+5)</p></div><button @click="schedule()">+ Добавить расписание</button></div><div class="table-scroll" v-if="settings.rows.length"><table><thead><tr><th>Получатель</th><th>Валюта</th><th>Время</th><th>Статус</th><th>Последняя отправка</th><th></th></tr></thead><tbody><tr v-for="r in settings.rows"><td>{{r.recipient}}</td><td>{{r.currency}}</td><td>{{String(r.hour).padStart(2,'0')}}:00</td><td><span class="badge">{{r.enabled?'Включена':'Черновик'}}</span><small>{{r.last_error}}</small></td><td>{{r.last_sent||'Ещё не отправляли'}}</td><td><button class="secondary tiny" @click="schedule(r)">Изменить</button><button class="ghost" @click="removeSchedule(r)">Удалить</button></td></tr></tbody></table></div><div v-else class="empty-state"><div class="empty-icon" aria-hidden="true">✉</div><h2>Отчёты в нужное время</h2><p>Выберите получателя, валюту и час отправки.<br>Расписание можно сохранить до подключения почты.</p><button @click="schedule()">+ Добавить расписание</button></div></section></template>
 <section v-if="page==='profile'" class="card"><p class="eyebrow">ЛИЧНАЯ УЧЁТНАЯ ЗАПИСЬ</p><h2>{{user.name}}</h2><p>{{user.username}} · {{user.role_label}}</p><button @click="changePassword">Изменить пароль</button><p class="muted">Сессия действует 60 минут. После смены пароля все сессии отзываются.</p></section>
 <footer class="workspace-footer">UZGERMED Treasury · Реестр операций и историческая FinModel разделены <span>Учёт без смешения валют</span></footer></main></div>
 <div v-if="modal" class="modal-backdrop"><form v-modal-focus class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" @submit.prevent="save" @keydown.esc="!saving&&(modal=null)"><div class="section-head"><h2 id="modal-title">{{modal.title}}</h2><button type="button" class="ghost" @click="modal=null" :disabled="saving">✕</button></div><p v-if="modal.note" class="form-note">{{modal.note}}</p><div class="form-grid"><label v-for="f in modalFields" :key="f.key" :class="{wide:f.type==='textarea'}">{{f.label}}<select v-if="f.type==='select'" v-model="form[f.key]" :required="f.required" :disabled="f.disabled"><option v-for="o in f.options" :value="o[0]">{{o[1]}}</option></select><textarea v-else-if="f.type==='textarea'" v-model="form[f.key]" :required="f.required" :minlength="f.minlength" maxlength="3000"></textarea><input v-else v-model="form[f.key]" :type="amountFields.includes(f.key)?'text':f.type" :inputmode="amountFields.includes(f.key)?'decimal':undefined" :pattern="amountFields.includes(f.key)?'[0-9]+([.][0-9]{1,2})?':undefined" :required="f.required" :disabled="f.disabled" :min="f.min" :max="f.max" :minlength="f.minlength" :step="f.step||'0.01'"></label></div><p v-if="categoryHint" class="warning category-hint" role="status">{{categoryHint}}</p><p v-if="formError" class="error">{{formError}}</p><div class="form-actions"><button type="button" class="secondary" @click="modal=null" :disabled="saving">Отмена</button><button :disabled="saving">{{saving?'Сохраняем…':modal.saveLabel||'Сохранить'}}</button></div></form></div>
 <div v-if="documents" class="modal-backdrop"><section class="modal"><div class="section-head"><h2>Документы · {{documents.ledger.reference}}</h2><button class="ghost" @click="documents=null">✕</button></div><p v-for="d in documents.rows"><a :href="d.url">{{d.filename}} ↓</a></p><p v-if="!documents.rows.length">Документов пока нет.</p><label v-if="has('write')" class="button">Прикрепить PDF / изображение<input type="file" accept=".pdf,.png,.jpg,.jpeg" @change="attach" :disabled="saving" hidden></label><p class="muted">До 5 МБ. Документы доступны только авторизованным пользователям с правом просмотра реестра.</p></section></div>
</template>
