<script setup>
import {ref,onMounted,watch} from 'vue';
const props=defineProps({api:Function,refresh:Number});
const month=ref(''),from=ref(''),to=ref(''),person=ref(''),action=ref(''),technical=ref(false),users=ref([]),actions=ref([]),items=ref([]),total=ref(0),page=ref(1),shown=ref(false),busy=ref(false),error=ref('');
const types={account:'Счёт',ledger:'Операция',request:'Заявка',category:'Статья',budget:'Бюджет',cash_plan:'План Cash Flow',user:'Пользователь',receipt:'Поступление',setting:'Настройка',import:'Импорт'};
function chooseMonth(){if(!month.value)return;from.value=month.value+'-01';const [y,m]=month.value.split('-').map(Number);to.value=month.value+'-'+new Date(y,m,0).getDate();shown.value=false}
function invalidate(){shown.value=false}
watch(()=>props.refresh,()=>{if(shown.value)load(page.value)});
async function load(p=1){if(from.value&&to.value&&from.value>to.value){error.value='Начало периода позже окончания';return}busy.value=true;error.value='';try{const q=new URLSearchParams({page:String(p),technical:String(technical.value)});if(from.value)q.set('date_from',from.value);if(to.value)q.set('date_to',to.value);if(person.value)q.set('user_id',person.value);if(action.value)q.set('action',action.value);const d=await props.api('/api/audit/history?'+q);items.value=d.items;total.value=d.total;users.value=d.users;actions.value=d.actions;page.value=p;shown.value=true}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{const d=await props.api('/api/audit/history?page_size=1');users.value=d.users;actions.value=d.actions}catch(e){error.value=e.message}});
</script>
<template><section class="card"><h2>История изменений</h2><form class="audit-filters" @submit.prevent="load(1)"><label>Месяц<input type="month" v-model="month" @change="chooseMonth"></label><label>С даты<input type="date" v-model="from" @change="month='';invalidate()"></label><label>По дату<input type="date" v-model="to" @change="month='';invalidate()"></label><label>Сотрудник<select v-model="person" @change="invalidate"><option value="">Все сотрудники</option><option v-for="u in users" :value="u.id">{{u.name}}</option></select></label><label>Действие<select v-model="action" @change="invalidate"><option value="">Все действия</option><option v-for="a in actions">{{a}}</option></select></label><button :disabled="busy">{{busy?'Поиск…':'Показать'}}</button></form><details class="help"><summary>Дополнительно</summary><label class="check-inline"><input type="checkbox" v-model="technical" @change="invalidate">Технические события</label></details></section><p v-if="error" class="error" role="alert">{{error}}</p><section v-if="!shown" class="empty-state"><h2>Найдите нужное действие</h2><p>Выберите период или сотрудника и нажмите «Показать».</p></section><template v-else><div class="section-head"><h3>Найдено событий: {{total}}</h3><span>Время Ташкента</span></div><ol class="audit-history"><li v-for="r in items" :key="r.id"><time>{{r.date}}</time><div><strong>{{r.user}}</strong><p>{{r.action}}</p><small v-if="types[r.entity]">{{types[r.entity]}} {{r.entity_id}}</small><details v-if="r.detail"><summary>Подробности</summary><p class="audit-detail">{{r.detail}}</p></details></div></li></ol><p v-if="!items.length" class="empty">За выбранный период событий нет.</p><div class="pagination"><span>Страница {{page}} из {{Math.max(1,Math.ceil(total/20))}}</span><div class="actions"><button class="secondary" :disabled="page<=1||busy" @click="load(page-1)">← Назад</button><button class="secondary" :disabled="page*20>=total||busy" @click="load(page+1)">Далее →</button></div></div></template></template>
