<script setup>
import {ref,computed,watch,nextTick} from 'vue';
const props=defineProps({report:Object,currency:String,year:[String,Number],api:Function,canPlan:Boolean});
const emit=defineEmits(['refresh','year']);
const months=['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'];
const mode=ref('actual'),start=ref(1),end=ref(12),collapsed=ref([]),editor=ref(false),editMonth=ref(1),draft=ref([]),opening=ref(''),reason=ref(''),error=ref(''),saving=ref(false),saved=ref(false);
const indices=computed(()=>Array.from({length:Number(end.value)-Number(start.value)+1},(_,i)=>i+Number(start.value)-1));
watch(start,()=>{if(Number(start.value)>Number(end.value))end.value=start.value});
watch(end,()=>{if(Number(end.value)<Number(start.value))start.value=end.value});
watch(()=>[props.currency,props.year],()=>{editor.value=false;saved.value=false});
const cents=v=>{if(v==null)return null;const [a,b='']=String(v).split('.');return BigInt(a)*100n+BigInt(b.padEnd(2,'0'))*(a.startsWith('-')?-1n:1n)};
const amount=n=>n==null?null:(n<0?'-':'')+(n<0?-n:n)/100n+'.'+String((n<0?-n:n)%100n).padStart(2,'0');
const difference=(a,b)=>a==null||b==null?null:amount(cents(a)-cents(b));
const display=v=>v==null?'Не задан':String(v).replace(/\B(?=(\d{3})+(?!\d))/g,' ');
const sum=values=>values.some(v=>v==null)?null:amount(values.reduce((n,v)=>n+cents(v),0n));
const columns=computed(()=>mode.value==='plan'?['plan','values','delta']:['values']);
const label={plan:'План',values:'Факт',delta:'Отклонение'};
const groups=computed(()=>props.report.groups.map(g=>({...g,rows:props.report.rows.filter(r=>r.activity===g.activity)})));
const summary=computed(()=>[
 {key:'opening',category:'Остаток на начало',values:props.report.opening,plan:props.report.plan_opening},
 {key:'net',category:'Чистое изменение денег',values:props.report.totals,plan:props.report.plan_totals},
 ...(props.report.opening_adjustments.some(v=>v!=='0.00')?[{key:'adjustment',category:'Ввод начальных остатков',values:props.report.opening_adjustments,plan:Array(12).fill(null)}]:[]),
 {key:'closing',category:'Остаток на конец',values:props.report.closing,plan:props.report.plan_closing}
]);
function value(row,m,column){return column==='delta'?difference(row.values[m],row.plan[m]):row[column][m]}
function aggregate(row,column){const calc=key=>row.key==='opening'?row[key][indices.value[0]]:row.key==='closing'?row[key][indices.value.at(-1)]:sum(indices.value.map(m=>row[key][m]));return column==='delta'?difference(calc('values'),calc('plan')):calc(column)}
function toggle(key){collapsed.value=collapsed.value.includes(key)?collapsed.value.filter(k=>k!==key):[...collapsed.value,key]}
const exportUrl=ext=>`/api/export/report.${ext}?year=${props.year}&currency=${props.currency}&mode=${mode.value}&start_month=${start.value}&end_month=${end.value}`;
async function edit(){editMonth.value=Number(start.value);editor.value=true;saved.value=false;resetDraft();await nextTick();document.querySelector('.plan-editor')?.scrollIntoView({block:'start'})}
function resetDraft(){const m=Number(editMonth.value)-1;draft.value=props.report.rows.map(r=>({category:r.category,category_id:r.category_id,kind:r.kind,amount:r.plan[m]==null?'':r.plan[m].replace('-','')}));opening.value=props.report.plan_opening_input[m]??'';reason.value='';error.value=''}
async function save(){saving.value=true;error.value='';try{await props.api('/api/cash-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:`${props.year}-${String(editMonth.value).padStart(2,'0')}`,currency:props.currency,version:props.report.plan_versions[Number(editMonth.value)-1],opening:opening.value===''?null:String(opening.value),reason:reason.value,items:draft.value.map(({category,...r})=>({...r,amount:r.amount===''?null:String(r.amount)}))})});editor.value=false;saved.value=true;emit('refresh')}catch(e){error.value=e.message}finally{saving.value=false}}
</script>
<template>
 <div class="report-heading"><div><span class="badge">Денежные потоки · {{currency}}</span><p class="report-caption">Поступления, выплаты и остатки</p></div><div class="actions"><a class="button secondary" :href="exportUrl('xlsx')">Excel</a><a class="button secondary" :href="exportUrl('pdf')">PDF</a><button v-if="canPlan" @click="edit">Задать план</button></div></div>
 <div class="filter-bar"><label>Год<input aria-label="Год отчёта" type="number" min="2000" max="2099" :value="year" @change="emit('year',$event.target.value)"></label><label>С месяца<select v-model="start"><option v-for="(m,i) in months" :value="i+1">{{m}}</option></select></label><label>По месяц<select v-model="end"><option v-for="(m,i) in months" :value="i+1">{{m}}</option></select></label><div class="segmented" role="group" aria-label="Вид отчёта"><button :aria-pressed="mode==='actual'" :class="{selected:mode==='actual'}" @click="mode='actual'">Факт</button><button :aria-pressed="mode==='plan'" :class="{selected:mode==='plan'}" @click="mode='plan'">План-факт</button></div></div>
 <p v-if="saved" class="notice" role="status">План сохранён</p>
 <div class="cash-summary"><div><span>На начало периода</span><strong>{{display(report.opening[indices[0]])}}</strong></div><div><span>Чистое изменение</span><strong>{{display(sum(indices.map(m=>report.totals[m])))}}</strong><small v-if="sum(indices.map(m=>report.opening_adjustments[m]))!=='0.00'">Ввод остатков: {{display(sum(indices.map(m=>report.opening_adjustments[m])))}}</small></div><div><span>На конец периода</span><strong>{{display(report.closing[indices.at(-1)])}}</strong></div></div>
 <div class="table-card cashflow-table report-grid" role="region" aria-label="Cash Flow по месяцам" tabindex="0"><table><thead><tr><th :rowspan="mode==='plan'?2:1">Статья</th><th v-for="m in indices" :colspan="columns.length" class="num">{{months[m]}}</th><th v-if="indices.length>1" :colspan="columns.length" class="num">За период</th></tr><tr v-if="mode==='plan'"><template v-for="m in indices.length>1?[...indices,'total']:indices"><th v-for="col in columns" class="num">{{label[col]}}</th></template></tr></thead><tbody>
 <tr class="report-total"><td>{{summary[0].category}}</td><template v-for="m in indices"><td v-for="col in columns" class="num">{{display(value(summary[0],m,col))}}</td></template><td v-for="col in indices.length>1?columns:[]" class="num">{{display(aggregate(summary[0],col))}}</td></tr>
 <template v-for="g in groups" :key="g.activity"><tr class="report-group"><td><button class="ghost" :aria-expanded="!collapsed.includes(g.activity)" @click="toggle(g.activity)">{{collapsed.includes(g.activity)?'▸':'▾'}} {{g.name}}</button></td><template v-for="m in indices"><td v-for="col in columns" class="num">{{display(value(g,m,col))}}</td></template><td v-for="col in indices.length>1?columns:[]" class="num">{{display(aggregate(g,col))}}</td></tr><template v-if="!collapsed.includes(g.activity)"><tr v-for="r in g.rows" :key="r.key"><td><span class="flow-direction">{{r.kind==='in'?'↓ Поступление':'↑ Выплата'}}</span>{{r.category}}</td><template v-for="m in indices"><td v-for="col in columns" class="num" :class="{'negative':col!=='plan'&&value(r,m,col)?.startsWith('-')}">{{display(value(r,m,col))}}</td></template><td v-for="col in indices.length>1?columns:[]" class="num">{{display(aggregate(r,col))}}</td></tr></template></template>
 <tr v-for="r in summary.slice(1)" class="report-total" :class="{'report-closing':r.key==='closing'}"><td>{{r.category}}</td><template v-for="m in indices"><td v-for="col in columns" class="num">{{display(value(r,m,col))}}</td></template><td v-for="col in indices.length>1?columns:[]" class="num">{{display(aggregate(r,col))}}</td></tr>
 </tbody></table></div>
 <details class="help"><summary>Как читать отчёт</summary><p>Прямой метод: поступления со знаком плюс, выплаты — минус. Отклонение = факт − план; отрицательное отклонение выплаты означает превышение плана. План платежей задаётся отдельно от лимитов бюджета. Пока не заполнены все статьи, итог плана не определён. Введите ноль для статей без планируемых движений. Остатки за период не суммируются. Счета учитываются в своей валюте, внутренние переводы исключены. Ввод начальных остатков после начала года показан отдельно от денежного потока.</p></details>
 <section v-if="editor" class="card plan-editor" aria-label="План денежных потоков"><div class="section-head"><h2>План · {{year}} · {{currency}}</h2><button class="ghost" @click="editor=false" :disabled="saving">Закрыть</button></div><form @submit.prevent="save"><div class="filter-bar"><label>Месяц<select v-model="editMonth" @change="resetDraft" :disabled="saving"><option v-for="(m,i) in months" :value="i+1">{{m}}</option></select></label><label>Плановый остаток на начало<input v-model="opening" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" placeholder="Из предыдущего плана"></label><button type="button" class="secondary" :disabled="saving" @click="draft.forEach(r=>{if(r.amount==='')r.amount='0'})">Пустые суммы → 0</button></div><p>Пустая сумма — план не задан. Укажите 0, если движения не планируются.</p><div class="plan-rows"><label v-for="r in draft"><span>{{r.category}}<small>{{r.kind==='in'?'Поступление':'Выплата'}}</small></span><input v-model="r.amount" :aria-label="r.category+' '+r.kind" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" placeholder="Не задан" :disabled="saving"></label></div><label class="plan-reason">Основание изменения<textarea v-model="reason" required minlength="10" maxlength="1000" :disabled="saving"></textarea></label><p v-if="error" class="error" role="alert">{{error}}</p><button :disabled="saving">{{saving?'Сохраняем…':'Сохранить план'}}</button></form></section>
</template>
