import {createApp} from 'vue';
import App from './App.vue';
import '@fontsource/manrope/cyrillic-400.css';
import '@fontsource/manrope/cyrillic-600.css';
import '@fontsource/manrope/latin-400.css';
import '@fontsource/manrope/latin-600.css';
import './style.css';
import './theme.css';
import './review.css';
createApp(App).mount('#app');
